export const Permissions= {
    "user": 
        {"menu":[
            {"moduleName":"Dashboard","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Resource Library","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"User Management","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Resort Management","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Approval Request","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Calendar","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Forum","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Certificates","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Subscription Model","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Course","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Training Class","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Quiz","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Video","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Document","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Notification","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Feedback","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Course Trend","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Training Class Trend","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Resort Details","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Certification Trend","view":true,"upload":false,"edit":false,"type":"web"}
        ],
        "menuMobile":[],
        "web":true,
        "mobile":false},
    "peeradmin": 
        {"menu":[
            {"moduleName":"Dashboard","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Resource Library","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"User Management","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Resort Management","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Approval Request","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Calendar","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Forum","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Certificates","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Subscription Model","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Course","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Training Class","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Quiz","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Video","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Document","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Notification","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Feedback","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Course Trend","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Training Class Trend","view":true,"upload":false,"edit":false,"type":"web"},
            {"moduleName":"Resort Details","view":true,"upload":true,"edit":true,"type":"web"},
            {"moduleName":"Certification Trend","view":true,"upload":true,"edit":true,"type":"web"}
        ],
        "menuMobile":[],
        "web":true,
        "mobile":false}
    }